# Generated by Django 3.1 on 2020-08-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.RenameModel(
            old_name="Stock",
            new_name="Product_Stock",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="retail_app.product_image",
            ),
        ),
    ]
