# Generated by Django 3.1 on 2020-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0007_auto_20200825_1825"),
    ]

    operations = [
        migrations.RemoveField(model_name="productimage", name="image",),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.CharField(default="default.jpg", max_length=255),
            preserve_default=False,
        ),
    ]
