# Generated by Django 3.1 on 2020-08-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0009_auto_20200831_1013"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcolor", options={"verbose_name_plural": "Product Color"},
        ),
        migrations.AddField(
            model_name="productcolor",
            name="quantity",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
