# Generated by Django 3.1 on 2020-08-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0010_auto_20200831_1121"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductQuantity",),
    ]
