# Generated by Django 3.1 on 2020-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0011_delete_productquantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productstock", old_name="color_stock", new_name="color",
        ),
        migrations.RemoveField(model_name="productcolor", name="quantity",),
        migrations.AddField(
            model_name="productstock",
            name="quantity",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
