# Generated by Django 3.1.1 on 2020-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0014_auto_20200916_0831"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductDescription",
        ),
        migrations.DeleteModel(
            name="ProductDetails",
        ),
        migrations.AlterField(
            model_name="productprice",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="currency",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
