# Generated by Django 3.1.1 on 2020-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0015_auto_20200928_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.TextField(),
        ),
    ]
