# Generated by Django 3.1.1 on 2020-10-02 13:14

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.manager
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0016_auto_20200928_1745"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("products_fully_loaded", django.db.models.manager.Manager()),
            ],
        ),
        BtreeGistExtension(),
        migrations.AddIndex(
            model_name="searchproductkeywords",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["keywords"], name="retail_app__keyword_7fc412_gist"
            ),
        ),
    ]
