# Generated by Django 3.1.1 on 2020-10-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0017_auto_20201001_1810"),
        ("retail_app", "0017_auto_20201002_1314"),
    ]

    operations = []
