# Generated by Django 3.1.1 on 2020-10-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail_app", "0018_merge_20201005_1238"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
    ]
